### PR TITLE
add esign store support

### PR DESCRIPTION
**Pull request by nklowns**
Hello, this is a minor change, but it would be interesting to have this for greater compatibility between sideloaders.
Apparently to work with esign we just need to update the downloadURL versions.

### CODE REVIEW

**Comment by nklowns** [comment]
I think it would be interesting to have the link to automatically add to the esign. @FouadRaheb

**Comment by sss8911** [comment]
Yes please

On 10 Sep 2024, at 9:11 PM, Cloud ***@***.***> wrote:

﻿

I think it would be interesting to have the link to automatically add to the esign. @FouadRaheb<https://github.com/FouadRaheb>

**Comment by sss8911** [comment]
Yes please

**Comment by FouadRaheb** [comment]
Thanks, I'll also update my script that generates the source json.

**Pull request merged**
